name: 🧪 Test Application

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]
  workflow_call:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'
        
    - name: Downgrade npm to compatible version
      run: npm install -g npm@7.24.2

    - name: Install dependencies
      run: npm install

    - name: Run linting
      run: npm run lint

    - name: Run unit tests
      run: npm run test

    - name: Run test coverage
      run: npm run test:cov

    - name: Build application
      run: npm run build

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      if: always()
